api = "0.10"

[buildpack]
id = "heroku-softtrends/redshift-odbc"
version = "0.0.1"
name = "Redshift ODBC Buildpack"
homepage = "https://github.com/heroku-softtrends/redshift-odbc-cnb"
[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "arm64"

[[targets]]
os = "linux"
arch = "amd64"
