api = "0.10"

[buildpack]
id = "heroku-softtrends/redshift-odbc"
version = "0.0.1"
name = "Redshift ODBC Buildpack"
homepage = "https://github.com/heroku-softtrends/redshift-odbc-cnb"

[[stacks]]
id = "*"  # Allows compatibility with all stacks

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "windows"
arch = "amd64"
