api = "0.8"

[buildpack]
id = "heroku/redshift-odbc"
version = "1.0.0"
name = "Redshift ODBC Buildpack"

[[stacks]]
id = "*"  # Allows compatibility with all stacks

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "windows"
arch = "amd64"
